### ISSUE TITLE
Nix Formatting

### ISSUE THREAD

**Issue by ahuston-0** [RAD-Development/nix-dotfiles#63]
**Issue**
We need consistent formatting that most of the group can agree on. This has been discussed in #75, however the implementation work needs to be done.

**Background**
The rfc-0101 repo has been forked so we can do demo work against it, and we've forked nixpkgs-fmt as well since its in a language that some of us are familiar with (Rust) and seems to have a modular/composable rules engine that we can add our rules to.

**Comment by ahuston-0** [comment]
as per dennis, formatting rules as of PR #75 

https://github.com/RAD-Development/nix-dotfiles/pull/75#discussion_r1478920654

rules are WIP

**Comment by ahuston-0** [comment]
Testing work is being done here:
https://github.com/RAD-Development/rfc-0101

Currently using alejandra 3.0.0, nixfmt 0.6.0 and commit id d83302adb7f6b40a5ed6f91e83af94a6bf83436f of our fork of nixpkgs-fmt.

**Comment by ahuston-0** [comment]
Added a RAD specific example here:
https://github.com/RAD-Development/rfc-0101/tree/main/rad

**Comment by DerDennisOP** [comment]
> Testing work is being done here: https://github.com/RAD-Development/rfc-0101
> 
> Currently using alejandra 3.0.0, nixfmt 0.6.0 and commit id d83302adb7f6b40a5ed6f91e83af94a6bf83436f of our fork of nixpkgs-fmt.

uhm are you making sure you are using this RFC101 branch? https://github.com/piegamesde/nixfmt/tree/rfc101-style

**Comment by ahuston-0** [comment]
> > Testing work is being done here: https://github.com/RAD-Development/rfc-0101
> > Currently using alejandra 3.0.0, nixfmt 0.6.0 and commit id d83302adb7f6b40a5ed6f91e83af94a6bf83436f of our fork of nixpkgs-fmt.
> 
> Are you making sure you are using this RFC101 branch, not sure if you mean this by the version 0.6.0 of nixfmt? https://github.com/piegamesde/nixfmt/tree/rfc101-style Another option would be to wait till this pr is through, they started 2 month ago, so it should be done maybe in 2 more month?

Currently using the standard release of nixfmt, but am not necessarily opposed to trying `rfc-0101` branch of nixfmt. Would like to hold a call once you're done with finals to go over what we want to do with this.
